 const users = [{
  "fName": "Lesya",
  "lName": "Keene",
  "username": "lkeene0@discovery.com",
  "gender": "Female"
}, {
  "fName": "Suzanna",
  "lName": "Thorneywork",
  "username": "sthorneywork1@foxnews.com",
  "gender": "Female"
}, {
  "fName": "Shirl",
  "lName": "Castle",
  "username": "scastle2@dell.com",
  "gender": "Female"
}, {
  "fName": "Celestia",
  "lName": "Ashwin",
  "username": "cashwin3@uiuc.edu",
  "gender": "Female"
}, {
  "fName": "Tod",
  "lName": "Livingstone",
  "username": "tlivingstone4@joomla.org",
  "gender": "Bigender"
}, {
  "fName": "Adolpho",
  "lName": "Norkutt",
  "username": "anorkutt5@photobucket.com",
  "gender": "Male"
}, {
  "fName": "Bevvy",
  "lName": "Fairham",
  "username": "bfairham6@dailymotion.com",
  "gender": "Female"
}, {
  "fName": "Krista",
  "lName": "Mariaud",
  "username": "kmariaud7@constantcontact.com",
  "gender": "Female"
}, {
  "fName": "Orelia",
  "lName": "Hulke",
  "username": "ohulke8@cornell.edu",
  "gender": "Female"
}, {
  "fName": "Willa",
  "lName": "Liggens",
  "username": "wliggens9@facebook.com",
  "gender": "Female"
}, {
  "fName": "Merrile",
  "lName": "Biles",
  "username": "mbilesa@cocolog-nifty.com",
  "gender": "Female"
}, {
  "fName": "Elizabet",
  "lName": "Jewiss",
  "username": "ejewissb@simplemachines.org",
  "gender": "Female"
}, {
  "fName": "Westbrooke",
  "lName": "Roocroft",
  "username": "wroocroftc@myspace.com",
  "gender": "Genderqueer"
}, {
  "fName": "Amalie",
  "lName": "Iacovides",
  "username": "aiacovidesd@nba.com",
  "gender": "Female"
}, {
  "fName": "Mireielle",
  "lName": "Rains",
  "username": "mrainse@cargocollective.com",
  "gender": "Female"
}, {
  "fName": "Fey",
  "lName": "Rogeron",
  "username": "frogeronf@ask.com",
  "gender": "Female"
}, {
  "fName": "Howard",
  "lName": "Outright",
  "username": "houtrightg@un.org",
  "gender": "Male"
}, {
  "fName": "Elliot",
  "lName": "Stalman",
  "username": "estalmanh@independent.co.uk",
  "gender": "Male"
}, {
  "fName": "Flint",
  "lName": "Olver",
  "username": "folveri@cdc.gov",
  "gender": "Male"
}, {
  "fName": "Tatiana",
  "lName": "O' Faherty",
  "username": "tofahertyj@hexun.com",
  "gender": "Non-binary"
}]


